### ISSUE TITLE
MetricRecorder: Label Metrics with Resource Labels

### ISSUE THREAD

**Issue by oliverbaehler** [fluxcd/pkg#155]
Proposal:
I would like to group my Flux Metrics by labels or annotations (idc). The easiest way I could think of resolving that, was by labeling the metrics with the labels of the object the metric originates from.

So I guess we would have to simple label the metrics with the ref Objects labels here:

https://github.com/fluxcd/pkg/blob/main/runtime/metrics/recorder.go

This way I could create something like this

```
--- 
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: backend
  namespace: tenant1-ns1
  labels:
    metric.flux.io/group: "system"
spec:
  interval: 5m
  path: "./webapp/backend/"
  prune: true
  serviceAccountName: "test"
  sourceRef:
    kind: GitRepository
    name: webapp
    namespace: tenant1-ns2
```

And then query it via the label over prometheus. What do you guys think? This would greatly improve the monitoring Experience for flux resources imho. I am happy to contribute the changes if you like the idea
