### ISSUE TITLE
Create workflow to build project on MacOS

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/pkg#294]
Similar to the workflow created for source-controller, a new GitHub workflow could ensure that MacOS platform is always working for development purposes:

```
  # Runs 'make test' on macos-10.15 to assure development environment for 
  # contributors using MacOS.
  darwin-amd64:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: Restore Go cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/_temp/_github_home/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: make test
```
source: https://github.com/fluxcd/source-controller/blob/3dcb1420760d8aa0dfb5d496910fd3f9576aeb8a/.github/workflows/e2e.yaml#L107-L126

Depends on: https://github.com/fluxcd/pkg/issues/275
