### ISSUE TITLE
cloneRefName() does not support annotated git tags

### ISSUE THREAD

**Issue by bburky** [fluxcd/pkg#546]
cloneRefName() does not support annotated git tags and attempts to clone the annotated tag object's id as if it were a commit object. This causes the following error (with the tag's hash, not the commit):

```
unable to resolve commit object for 'da39a3ee5e6b4b0d3255bfef95601890afd80709': object not found
```

Currently Flux's `cloneRefName()` passes the ref to `getRemoteHEAD()` to resolve the ref to an object id, and then passes the id to `cloneCommit()` which only supports commit objects, not annotated tags.

A configuration like the following will trigger the error:

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: repository-name
spec:
  ref:
    name: refs/tags/an-annotated-git-tag
```

We accidentally stumbled across this when a new developer made the tag and they used an annotated tag not expecting there to be any difference at all for Flux. We had to a little bit of debugging to figure out that an annotated tag caused the issue. I think most users would expect any ref to work with `name:`.

* * * 

See #539 for discussion and https://github.com/fluxcd/pkg/pull/539#issuecomment-1534250857 for a proposed solution
