### ISSUE TITLE
Add version parameter to GitHub actions

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/pkg#6]
When using the pkg GitHub actions, we should able to override the binary version e.g.:

```yaml
      - name: Setup Kustomize
        uses: fluxcd/pkg/actions/kustomize@master
        with:
          version: 3.8.0
```
