### ISSUE TITLE
Build order gives higher priority to ASO ServiceBus Namespace kind above Kubernetes core API Namespace kind

### ISSUE THREAD

**Issue by danielwilsonkainos** [fluxcd/pkg#689]
### What happened?

Azure Service Operator (ASO) allows deployment and maintenance of a wide variety of Azure Resources using CRDs in a K8s native way.

One of the resources supported by ASO is [ServiceBus](https://azure.github.io/azure-service-operator/reference/servicebus/). ServiceBus has the conecept of namespacing for queues and topics and as such one of the sub-resources for setting up a ServiceBus is its [Namespace](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview#namespaces). 

The CRD for ServiceBus Namespace is as below: 

```yaml
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: aso-namespace
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard
  zoneRedundant: false
```

ServiceBus has its own _GroupValue_ apiVersion however its _Kind_ is **Namespace** which is the same _Kind_ as K8s core Namespace resource.

In the codebase there is the _IsLessThan_ function which has a [comparative sort](https://github.com/fluxcd/pkg/blob/main/ssa/sort.go#L127-137) which finalizes ordering for Kustomization.yaml. 

This contains [logic to order by _Kind_](https://github.com/fluxcd/pkg/blob/main/ssa/sort.go#L136) and [by Group](https://github.com/fluxcd/pkg/blob/main/ssa/sort.go#L133-L134) when the _Kinds_ are the same - giving a higher sort order by comparing group lexicographically. 

The lexiographical sort is causing the ServiceBus to placed at the top of the output Kustomization manifest and the core Namespace below. This causes failure as there is no Kubernetes namespace to deploy the ServiceBus Namespace into.

### What did you expect to happen?

Core API Namespace should be created first and be placed highest in the Kustomization.yaml output, above ServiceBus

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- core_namespace.yaml
- servicebus_namespace.yaml
```

```yaml
# core_namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
```

```yaml
# servicebus_namespace.yaml
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: aso-namespace
  namespace: test-namespace
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard
  zoneRedundant: false
```

### Expected output

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: aso-namespace
  namespace: test-namespace
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard
  zoneRedundant: false
```

### Actual output

```yaml
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: aso-namespace
  namespace: test-namespace
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard
  zoneRedundant: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
```

This bug is also encountered in Kustomize codebase where I have also [opened an issue/PR](https://github.com/kubernetes-sigs/kustomize/issues/5457)

**Comment by danielwilsonkainos** [comment]
I have raised a PR with a potential fix for this issue however there may be a better implementation - https://github.com/fluxcd/pkg/pull/690

**Comment by stefanprodan** [comment]
> This causes failure as there is no Kubernetes namespace to deploy the ServiceBus Namespace into.

This shouldn't cause such errors, as kustomize-controller applies the namespaces is different stage than all other objects. The controller uses this function https://github.com/fluxcd/pkg/blob/main/ssa/utils.go#L208-L211

**Comment by stefanprodan** [comment]
@danielwilsonkainos can you please post here the error log from Flux. I'm really puzzled about this bug report as the code in Flux will never apply things to namespaces unless those exist in the cluster.

**Comment by danielwilsonkainos** [comment]
Yes, of course. Let me elaborate a bit further on how we've come to this issue (albeit may have jumped to an incorrect conclusion)

We have issue with deploying through Flux to our k8s cluster only where ASO is being used to deploy a ServiceBus Namespace. When investigating we noticed that the output of _Kustomize build_ was ordering with ServiceBus Namespace above k8s namespace in its output which lead to opening this issue in the [Kustomize codebase](https://github.com/kubernetes-sigs/kustomize/issues/5457)

We're using Flux 2.0.1 which has support for _[SortOptions](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/sortoptions/)_ and changed [our Kustomization files](https://github.com/hmcts/cnp-flux-config/blob/master/apps/sscs/preview/base/kustomization.yaml) for these cases to use FIFO ordering to work around this, making sure that the k8s Namespace is specified before the ServiceBus namespace in resources list ([namespace](https://github.com/hmcts/cnp-flux-config/blob/master/apps/base/namespace.yaml) is in our base folder specified at the top of resources)

Locally using _Kustomize build_ the output ordering conforms to the expected result from the FIFO ordering. When the Kustomization is pulled through the Kustomize-Controller in Flux we see persistence of the initial error that we have encountered. The error is this:

`error Kustomization/sscs.flux-system - Reconciliation failed after 514.827695ms, next try in 1m0s Namespace/sscs/sscs-servicebus-preview namespace not specified: namespaces "sscs" not found`

We can apply the Kustomization manually as expected, however through the Kustomize-controller it hits the above error. For the _sscs_ app this is done with:

`flux build kustomization sscs --path ./apps/sscs/preview/00/ | kubectl apply -f -`

We noticed there is sorting applied and I saw similar logic to the sorting in Kustomize codebase. I've added the same logic in my PR thinking it may be duplication of the Kustomize issue however I have very limited developer experience and wouldn't know how to test this (Sorry)

Please let me know if there is any way i can help.

**Comment by stefanprodan** [comment]
kustomize-controller performs a multi-stage apply, first stage is for CRDs and Namespaces: https://github.com/fluxcd/kustomize-controller/blob/250f620fbe4d3bcfc3db517cfde581744842488e/internal/controller/kustomization_controller.go#L732-L733

The Kubernetes namespaces are extract with https://github.com/fluxcd/pkg/blob/main/ssa/utils.go#L208-L211 which I don't think it matches the servicebus object.

**Comment by stefanprodan** [comment]
@danielwilsonkainos I wrote a test in https://github.com/fluxcd/kustomize-controller/pull/1016 and I can't reproduce this issue. Can please post here `flux version`.

**Comment by danielwilsonkainos** [comment]
@stefanprodan Thank you very much for your efforts so far. GOTK versions are:

helm-controller: v0.35.0
kustomize-controller: v1.0.1
notification-controller: v1.0.0
source-controller: v1.0.1

I've destroyed and rebuilt our cluster this morning but the error still persists

**Comment by stefanprodan** [comment]
Can you please use latest Flux kustomize-controller **v1.1.1**.

**Comment by stefanprodan** [comment]
The error you posted `Namespace/sscs/sscs-servicebus-preview namespace not specified: namespaces "sscs" not found` it's also puzzling for me, it should be a dry-run error, not an apply error, as we do a dry-run before trying to apply. Is kustomize-controller you're running a custom build, is the code 1to1 with upstream?

**Comment by danielwilsonkainos** [comment]
Hi @stefanprodan - I've upgraded a cluster today for testing but the error is still being hit. The versions are now at:

helm-controller: v0.36.2
kustomize-controller: v1.1.1
notification-controller: v1.1.0
source-controller: v1.1.2

AFAIK the kustomize-controller should be 1to1 with upstream. [This is our bootstrap method](https://github.com/hmcts/aks-cft-deploy/blob/flux-v2.1.2-preview/bootstrap/scripts/install-flux.sh).

[This is our base for flux-system](https://github.com/hmcts/cnp-flux-config/blob/flux-v2.1.2-preview-base/apps/flux-system/base/kustomization.yaml). I've tested in our [preview environment](https://github.com/hmcts/cnp-flux-config/blob/flux-v2.1.2-preview-base/apps/flux-system/preview/base/kustomization.yaml). We only apply a [small patch](https://github.com/hmcts/cnp-flux-config/blob/flux-v2.1.2-preview-base/apps/flux-system/base/patches/kustomize-controller-patch.yaml) for azure auth.

Again, please let me know if theres anything i can do to help

**Comment by stefanprodan** [comment]
@danielwilsonkainos can you post here the exact YAMLs for the core namespace and the servicebus namespace, so I can use those in the tests.

**Comment by danielwilsonkainos** [comment]
of course:

namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    slackChannel: special-tribunals-builds
  name: sptribs
```

servicebus namespace:
```
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  annotations:
    serviceoperator.azure.com/reconcile-policy: detach-on-delete
  name: sptribs-servicebus-preview
  namespace: sptribs
spec:
  azureName: sptribs-sb-preview
  location: uksouth
  owner:
    name: sptribs-aso-preview-rg
  sku:
    name: Standard
  tags:
    app.kubernetes.io_name: special-tribunals
    application: special-tribunals
    builtFrom: https://github.com/hmcts/cnp-flux-config
    businessArea: CFT
    environment: development
  zoneRedundant: false
```
