### ISSUE TITLE
Why do we need to check for a strict semver in ParseVersion?

### ISSUE THREAD

**Issue by mo-rieger** [fluxcd/pkg#771]
I stumbled on this, when I was using an ImagePolicy with `policy.semver.range` defined.

Some repositories strip the patch version when doing a minor release, e.g. [kubernetes-event-exporter](https://github.com/resmoio/kubernetes-event-exporter/releases). The image-reflector-controller cant evaluate the latest tag of such tags and logs: `unable to determine latest version from provided list`.

<details><summary>ImagePolicy</summary>
<p>

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kubernetes-event-exporter
spec:
  imageRepositoryRef:
    name: kubernetes-event-exporter
  policy:
    semver:
      range: ^1.1
``` 

</p>
</details> 

We see this because we check for a strict semver in [ParseVersion](https://github.com/fluxcd/pkg/blob/main/version/version.go), even though `semver.NewVersion` is used to return the version which could actually handle missing patch versions, like `1.1`.
